spring:
  application:
    name: Poller
sid:
  poller:
    collector:
      snmp:
        cron: "0 0/2 * * * *"
        collectorTimeout: 180000
        workerTimeout: 5000
        size: 10
        queue: 1000
      ssh:
        cron: "0 1/2 * * * *"
        collectorTimeout: 180000
        workerTimeout: 5000
        size: 40
        queue: 1000
logging:
  level:
    es:
      vodafone:
        sid:
          poller: debug

