spring:
  application:
    name: Poller
sid:
  poller:
    collector:
      snmp:
        cron: "0 0/2 * * * *"
        timeout: 1800
        size: 10
        queue: 1000
      ssh:
        cron: "0 1/2 * * * *"
        timeout: 1800
        size: 40
        queue: 1000
    worker:
      snmp:
        timeout: 10000
      ssh:
        timeout: 10000
logging:
  level:
    es:
      vodafone:
        sid:
          poller: debug

